# Generated by Django 5.1.4 on 2025-06-05 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_Manager', '0001_initial'),
        ('unlisted_stock_marketplace', '0003_alter_customfieldvalue_text_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_difference_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share_name', models.CharField(max_length=775)),
                ('date_bought', models.DateField()),
                ('price_bought', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_shares', models.PositiveIntegerField(default=1)),
                ('price_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Holding', 'Holding'), ('Sold', 'Sold')], default='Holding', max_length=50)),
                ('invested_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('overall_gain_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale')], default='Purchase', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.Broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
