# Generated by Django 5.1.4 on 2025-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0002_buytransaction_selltransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selltransaction',
            name='price_per_share',
        ),
        migrations.RemoveField(
            model_name='selltransaction',
            name='total_amount',
        ),
    ]
