# Generated by Django 5.2.2 on 2025-06-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0006_alter_advisor_advisor_type_delete_advisortype'),
        ('unlisted_stock_marketplace', '0005_alter_customfieldvalue_field_definition_and_more'),
        ('user_portfolio', '0006_selltransaction_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransactionOtherAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.advisor')),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
