# Generated by Django 5.2.2 on 2025-06-14 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0006_alter_advisor_advisor_type_delete_advisortype'),
        ('unlisted_stock_marketplace', '0006_stockdailysnapshot_lot'),
        ('user_portfolio', '0006_selltransaction_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransactionOtherAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='completed', max_length=15)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('todays_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.advisor')),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStockInvestmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_held', models.PositiveIntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ltp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_day_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overall_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('day_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buy_order_count', models.PositiveIntegerField(default=0)),
                ('buy_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sell_order_count', models.PositiveIntegerField(default=0)),
                ('sell_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.advisor')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
