# Generated by Django 5.2.2 on 2025-06-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0007_buytransactionotheradvisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransactionotheradvisor',
            name='status',
        ),
    ]
