# Generated by Django 5.2.2 on 2025-06-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0008_remove_buytransactionotheradvisor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='completed', max_length=15),
        ),
    ]
