# Generated by Django 5.2.2 on 2025-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0008_selltransactionotheradvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransaction',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='buytransaction',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='selltransactionotheradvisor',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='selltransactionotheradvisor',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='processing', max_length=15),
        ),
    ]
