# Generated by Django 5.2.2 on 2025-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0009_buytransactionotheradvisor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='overall_gain_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='todays_gain_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
