# Generated by Django 5.2.2 on 2025-06-12 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0006_alter_advisor_advisor_type_delete_advisortype'),
        ('unlisted_stock_marketplace', '0005_alter_customfieldvalue_field_definition_and_more'),
        ('user_portfolio', '0010_buytransactionotheradvisor_invested_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockInvestmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_held', models.PositiveIntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ltp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_day_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overall_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('day_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buy_order_count', models.PositiveIntegerField(default=0)),
                ('buy_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sell_order_count', models.PositiveIntegerField(default=0)),
                ('sell_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.advisor')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
