# Generated by Django 5.2.2 on 2025-06-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0010_buytransaction_acapproved_buytransaction_rmapproved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selltransaction',
            name='ACApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_approved_sell_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='RMApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_approved_sell_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='STApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_approved_sell_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selltransactionotheradvisor',
            name='ACApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_approved_sell_otherAdvisor_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selltransactionotheradvisor',
            name='RMApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_approved_sell_otherAdvisor_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selltransactionotheradvisor',
            name='STApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_approved_sell_otherAdvisor_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
