# Generated by Django 5.2.2 on 2025-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0011_selltransaction_acapproved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransaction',
            name='AC_Payment_Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('approved', 'Payment Received'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='AC_Payment_Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('approved', 'Payment Received'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
