# Generated by Django 5.2.2 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0011_userstockinvestmentsummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstockinvestmentsummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userstockinvestmentsummary',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='userstockinvestmentsummary',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='userstockinvestmentsummary',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='userstockinvestmentsummary',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyTransactionOtherAdvisor',
        ),
        migrations.DeleteModel(
            name='UserStockInvestmentSummary',
        ),
    ]
