# Generated by Django 5.2.2 on 2025-06-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0012_buytransaction_ac_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selltransaction',
            name='AC_Payment_Status',
        ),
    ]
