# Generated by Django 5.2.2 on 2025-06-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0013_remove_selltransaction_ac_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='AC_Payment_Status',
        ),
    ]
