# Generated by Django 5.2.2 on 2025-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0014_remove_buytransaction_ac_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytransaction',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Share Transfer team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by AC')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Accounts team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by RM')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Transfer Share'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by ST')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='buytransactionotheradvisor',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Transfer Share'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by ST')], default='completed', max_length=15),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Share Transfer team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by AC')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Accounts team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by RM')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Transfer Share'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by ST')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='selltransactionotheradvisor',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Share Transfer team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by AC')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='selltransactionotheradvisor',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Accounts team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by RM')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='selltransactionotheradvisor',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Transfer Share'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by ST')], default='processing', max_length=15),
        ),
    ]
