# Generated by Django 5.2.4 on 2025-07-12 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0013_alter_stockhistory_timestamp'),
        ('user_portfolio', '0015_alter_buytransaction_ac_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstockinvestmentsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userstockinvestmentsummary',
            name='is_other_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='userstockinvestmentsummary',
            unique_together={('user', 'stock', 'is_other_advisor')},
        ),
    ]
