# Generated by Django 5.2.4 on 2025-08-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0016_alter_userstockinvestmentsummary_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='ACApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_approved_buy_other_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Share Transfer team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by AC')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='RMApproved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_approved_buy_other_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Accounts team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by RM')], default='processing', max_length=15),
        ),
    ]
