# Generated by Django 5.2.4 on 2025-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0017_buytransactionotheradvisor_acapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytransactionotheradvisor',
            name='AC_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Share Transfer team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by AC')], default='completed', max_length=15),
        ),
        migrations.AlterField(
            model_name='buytransactionotheradvisor',
            name='RM_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Process to Accounts team'), ('on_hold', 'On Hold'), ('cancelled', 'Rejected by RM')], default='completed', max_length=15),
        ),
    ]
