# Generated by Django 5.2.4 on 2025-08-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0018_alter_buytransactionotheradvisor_ac_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buytransactionotheradvisor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='selltransactionotheradvisor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
