# Generated by Django 5.2.4 on 2025-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0019_buytransaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockinvestmentsummary',
            name='day_gain_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='userstockinvestmentsummary',
            name='overall_gain_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
