# Generated by Django 5.2.4 on 2025-09-08 05:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0014_alter_event_paragraph'),
        ('unlisted_stock_marketplace', '0020_stockdata_youtube_video_link'),
        ('user_portfolio', '0020_userstockinvestmentsummary_day_gain_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstockinvestmentsummary',
            unique_together={('user', 'stock', 'broker', 'is_other_advisor')},
        ),
    ]
