# Generated by Django 5.2.4 on 2025-09-08 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0014_alter_event_paragraph'),
        ('unlisted_stock_marketplace', '0020_stockdata_youtube_video_link'),
        ('user_portfolio', '0021_alter_userstockinvestmentsummary_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstockinvestmentsummary',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userstockinvestmentsummary',
            constraint=models.UniqueConstraint(fields=('user', 'stock', 'advisor', 'broker', 'is_other_advisor'), name='uniq_user_stock_advisor_broker_bucket'),
        ),
    ]
