# Generated by Django 5.1.4 on 2025-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('RM', 'Relationship Manager'), ('AC', 'Accounts'), ('SM', 'Site Manager'), ('ST', 'Share Transfer'), ('AD', 'Admin'), ('DF', 'Default User'), ('AP', 'Associate Partner'), ('PT', 'Partner'), ('Other', 'Other')], default='DF', max_length=5),
        ),
    ]
