# Generated by Django 5.1.7 on 2025-04-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_broker_userprofile_whatsapp_number_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='broker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='broker_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
