# Generated by Django 5.1.4 on 2025-06-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmrcopy',
            old_name='client',
            new_name='user_profile',
        ),
    ]
