# Generated by Django 5.1.4 on 2025-06-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0004_alter_broker_id'),
        ('user_auth', '0003_rename_client_cmrcopy_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmrcopy',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_Manager.Broker'),
        ),
    ]
