# Generated by Django 5.1.4 on 2025-05-01 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_broker_email_broker_phone_number_broker_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmrcopy',
            name='cmr_file',
            field=models.FileField(blank=True, help_text='Upload a scanned copy or PDF', null=True, upload_to='cmr_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
