# Generated by Django 5.1.4 on 2025-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_cmrcopy_cmr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('RM', 'Relationship Manager'), ('AC', 'Accounts'), ('SM', 'Site Manager'), ('AD', 'Admin'), ('DF', 'Default User')], default='DF', max_length=2),
        ),
    ]
