# Generated by Django 5.1.4 on 2025-06-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_cmrcopy_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmrcopy',
            name='broker',
        ),
        migrations.AddField(
            model_name='cmrcopy',
            name='broker_id',
            field=models.CharField(blank=True, help_text='Selected Broker ID', max_length=50, null=True),
        ),
    ]
