# Generated by Django 5.1.4 on 2025-06-06 04:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0004_alter_broker_id'),
        ('user_auth', '0005_remove_cmrcopy_broker_cmrcopy_broker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmrcopy',
            name='broker_id',
        ),
        migrations.AddField(
            model_name='cmrcopy',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Select a broker from the list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.Broker'),
        ),
        migrations.AlterField(
            model_name='cmrcopy',
            name='cmr_file',
            field=models.FileField(blank=True, null=True, upload_to='cmr_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
