# Generated by Django 5.1.4 on 2025-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('RM', 'Relationship Manager'), ('AC', 'Accounts'), ('SM', 'Site Manager'), ('AD', 'Admin'), ('DF', 'Default User'), ('AP', 'Associate Partner'), ('PT', 'Partner')], default='DF', max_length=2),
        ),
    ]
