# Generated by Django 5.1.4 on 2025-06-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_remove_cmrcopy_broker_id_cmrcopy_broker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmrcopy',
            name='broker_id_input',
        ),
    ]
