# Generated by Django 5.1.4 on 2025-06-07 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_remove_cmrcopy_broker_id_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_rm',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'RM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
