# Generated by Django 5.1.4 on 2025-06-08 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_customuser_assigned_rm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_email', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_phone', to=settings.AUTH_USER_MODEL, to_field='phone_number', validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter valid phone number')]),
        ),
    ]
