# Generated by Django 5.2.2 on 2025-06-12 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4,5}[0-9]{3,4}[A-Z]$', 'Enter valid PAN number')]),
        ),
    ]
