# Generated by Django 5.2.2 on 2025-06-14 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_alter_userprofile_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='statementPaper',
            field=models.FileField(blank=True, null=True, upload_to='bank_statements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx'])]),
        ),
    ]
