# Generated by Django 5.2.2 on 2025-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_alter_userprofile_pan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(help_text="Use '--' before each point for lists.")),
                ('style', models.CharField(choices=[('paragraph', 'Paragraph'), ('ul', 'Unordered List'), ('ol_number', 'Ordered List (Numbered)'), ('ol_alpha', 'Ordered List (Alphabetical)')], default='paragraph', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
