# Generated by Django 5.2.2 on 2025-06-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='FAQ_G',
        ),
    ]
