# Generated by Django 5.2.2 on 2025-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_rename_faq_faq_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_g',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
