# Generated by Django 5.2.4 on 2025-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_contact_sent_at_contact_subject_contact_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('RM', 'Relationship Manager'), ('AC', 'Accounts'), ('SM', 'Site Manager'), ('ST', 'Share Transfer'), ('AD', 'Admin'), ('DF', 'Default User'), ('AP', 'Associate Partner'), ('Other', 'Other')], default='DF', max_length=5),
        ),
    ]
