# Generated by Django 5.2.4 on 2025-08-12 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0019_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adhar_card_photo',
            field=models.FileField(blank=True, null=True, upload_to='adhar_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pan_card_photo',
            field=models.FileField(blank=True, null=True, upload_to='pan_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
