# Generated by Django 5.2.4 on 2025-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_alter_userprofile_adhar_card_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adhar_doc_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_doc_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
