# Generated by Django 5.2.4 on 2025-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_userprofile_adhar_doc_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bankDetails_doc_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
