# Generated by Django 5.2.4 on 2025-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('saving', 'Saving'), ('current', 'Current'), ('salary', 'Salary'), ('nre', 'NRE'), ('nro', 'NRO')], default='saving', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='linked_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
