# Generated by Django 5.2.4 on 2025-08-18 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0024_alter_bankaccount_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digit phone number (digits only).', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number.')]),
        ),
    ]
