# Generated by Django 5.2.4 on 2025-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0028_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='residency_status',
            field=models.CharField(choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], default='Resident', max_length=20),
        ),
    ]
