# Generated by Django 5.2.4 on 2025-09-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0029_customuser_residency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='document_type',
            field=models.CharField(choices=[('cancelled_cheque', 'Cancelled Cheque'), ('bank_statement', 'One Month Bank Statement'), ('passbook', 'Front Page of Passbook')], default='cancelled_cheque', max_length=20),
        ),
    ]
