# Generated by Django 5.2.4 on 2025-09-10 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0030_bankaccount_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('saving', 'Saving'), ('current', 'Current'), ('salary', 'Salary'), ('nre', 'NRE'), ('nro', 'NRO'), ('jointAcc', 'Joint Account')], default='saving', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='document_type',
            field=models.CharField(choices=[('cancelled_cheque', 'Cancelled Cheque'), ('bank_statement', 'Bank Statement'), ('passbook', 'Passbook')], default='cancelled_cheque', max_length=20),
        ),
        migrations.CreateModel(
            name='JointAccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('aadhaar_doc', models.FileField(upload_to='kyc/aadhaar/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('aadhaar_doc_password', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_doc', models.FileField(upload_to='kyc/pan/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('pan_doc_password', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_holders', to='user_auth.bankaccount')),
            ],
        ),
    ]
