# Generated by Django 5.1.4 on 2025-06-02 15:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=775, null=True)),
                ('scrip_name', models.CharField(blank=True, max_length=775, null=True)),
                ('isin_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=775, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('drhp_filed', models.BooleanField(default=False)),
                ('available_on', models.CharField(blank=True, max_length=50, null=True)),
                ('rofr_require', models.BooleanField(default=False)),
                ('outstanding_shares', models.BigIntegerField(blank=True, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ps_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pbv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lifetime_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lifetime_high_date', models.DateField(blank=True, null=True)),
                ('lifetime_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lifetime_low_date', models.DateField(blank=True, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lot', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('conviction_level', models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Very High', max_length=50, null=True)),
                ('number_of_times_searched', models.PositiveIntegerField(default=0)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stock_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('company_overview', models.TextField(blank=True, null=True)),
                ('registered_office_address', models.TextField(blank=True, null=True)),
                ('transfer_agent_address', models.TextField(blank=True, null=True)),
                ('stock_type', models.CharField(blank=True, choices=[('Unlisted', 'Unlisted'), ('Angel', 'Angel'), ('Listed', 'Listed')], default='Unlisted', help_text='Type of stock: Unlisted, Angel, or Listed', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(blank=True, max_length=775, null=True)),
                ('number_of_shares', models.BigIntegerField(blank=True, null=True)),
                ('percentage_of_total', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=775, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalBusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_service_name', models.CharField(blank=True, max_length=775, null=True, verbose_name='Name and Description of main products/services')),
                ('nic_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIC Code of the product/service')),
                ('turnover_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% to total turnover of the Company')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_activities', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, help_text='Enter the FAQ question. Symbols like ₹, %, etc. are supported.', null=True)),
                ('answer', models.TextField(blank=True, help_text='Provide a clear, concise answer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=775, null=True)),
                ('position', models.CharField(blank=True, max_length=775, null=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_title', models.CharField(blank=True, help_text="Friendly section title for UI (e.g., 'Non-current assets')", max_length=775, null=True)),
                ('model_type', models.CharField(blank=True, choices=[('FinancialRatios', 'Financial Ratios'), ('BalanceSheet', 'Balance Sheet'), ('ProfitLossStatement', 'Profit & Loss Statement'), ('CashFlow', 'Cash Flow'), ('DividendHistory', 'Dividend History')], max_length=50, null=True)),
                ('custom_model_name', models.CharField(blank=True, help_text="Optional custom model name (e.g., 'CustomRatios')", max_length=100, null=True)),
                ('unit', models.CharField(blank=True, choices=[('', 'None'), ('₹', 'Rupee (₹)'), ('$', 'Dollar ($)'), ('€', 'Euro (€)'), ('%', 'Percentage (%)'), ('bps', 'Basis Points (bps)'), ('x', 'Multiplier (x)'), ('Cr', 'Crore (Cr)'), ('L', 'Lakh (L)'), ('M', 'Million (M)'), ('B', 'Billion (B)'), ('Units', 'Units')], max_length=10, null=True)),
                ('stock', models.ForeignKey(blank=True, help_text='Associate this field with a specific stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=775, null=True)),
                ('relation_type', models.CharField(blank=True, choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate'), ('WhollyOwnedSubsidiary', 'Wholly Owned Subsidiary'), ('StepDownSubsidiary', 'Step Down Subsidiary'), ('JointVenture', 'Joint Venture')], max_length=30, null=True)),
                ('percentage_shares_held', models.DecimalField(blank=True, decimal_places=4, help_text='Enter percentage (e.g., 75.00)', max_digits=7, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_difference_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share_name', models.CharField(max_length=775)),
                ('date_bought', models.DateField()),
                ('price_bought', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_shares', models.PositiveIntegerField(default=1)),
                ('price_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Holding', 'Holding'), ('Sold', 'Sold')], default='Holding', max_length=50)),
                ('invested_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('overall_gain_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale')], default='Purchase', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.Broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Leave blank if stock period is used as title', max_length=775, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the table display')),
                ('stock_period', models.ForeignKey(blank=True, help_text='If provided, will override the title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_headers', to='unlisted_stock_marketplace.stockperiod')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=775, null=True)),
                ('description', models.TextField(blank=True, max_length=775, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('dec_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('char_value', models.TextField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('text_style', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline')], default='normal', max_length=30)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.customfielddefinition')),
                ('parent_field_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_field_values', to='unlisted_stock_marketplace.customfieldvalue')),
                ('table_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values', to='unlisted_stock_marketplace.tableheader')),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
            },
        ),
        migrations.CreateModel(
            name='WishlistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('conviction_level', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Yesterday's Close (LTP)")),
                ('share_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Today's Opening Price")),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='unlisted_stock_marketplace.stockdata')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='unlisted_stock_marketplace.wishlistgroup')),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
