# Generated by Django 5.1.4 on 2025-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailysnapshot',
            name='ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yesterdays Close (LTP)'),
        ),
    ]
