# Generated by Django 5.1.4 on 2025-06-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0002_alter_stockdailysnapshot_ltp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('bold_italic', 'Bold & Italic'), ('bold_underline', 'Bold & Underline'), ('italic_underline', 'Italic & Underline'), ('all', 'Bold, Italic & Underline')], default='normal', max_length=30),
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
