# Generated by Django 5.1.7 on 2025-04-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(max_length=255)),
                ('number_of_shares', models.BigIntegerField()),
                ('total_company_shares', models.BigIntegerField(editable=False)),
                ('percentage_of_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
    ]
