# Generated by Django 5.1.7 on 2025-04-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0003_shareholdingpattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholdingpattern',
            name='total_company_shares',
        ),
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='percentage_of_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
