# Generated by Django 5.2.2 on 2025-06-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0003_alter_customfieldvalue_text_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='custom_model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic')], default='normal', max_length=30),
        ),
    ]
