# Generated by Django 5.2.2 on 2025-06-10 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0004_alter_customfielddefinition_custom_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='field_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='unlisted_stock_marketplace.customfielddefinition'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline')], default='normal', max_length=30),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['field_definition'], name='unlisted_st_field_d_19a449_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['parent_field_value'], name='unlisted_st_parent__f78385_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['table_header'], name='unlisted_st_table_h_751009_idx'),
        ),
    ]
