# Generated by Django 5.1.7 on 2025-04-11 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0004_remove_shareholdingpattern_total_company_shares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('field_type', models.CharField(choices=[('char', 'Text'), ('int', 'Integer'), ('dec', 'Decimal'), ('date', 'Date')], max_length=10)),
                ('unit', models.CharField(blank=True, choices=[('', 'None'), ('₹', 'Rupee (₹)'), ('$', 'Dollar ($)'), ('€', 'Euro (€)'), ('%', 'Percentage (%)'), ('bps', 'Basis Points (bps)'), ('x', 'Multiplier (x)'), ('Cr', 'Crore (Cr)'), ('L', 'Lakh (L)'), ('M', 'Million (M)'), ('B', 'Billion (B)'), ('Units', 'Units')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='conviction_level',
            field=models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Very High', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('dec_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('char_value', models.TextField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlisted_stock_marketplace.customfielddefinition')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='unlisted_stock_marketplace.stockdata')),
            ],
            options={
                'unique_together': {('stock', 'field_definition')},
            },
        ),
    ]
