# Generated by Django 5.2.2 on 2025-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0005_alter_customfieldvalue_field_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdailysnapshot',
            name='lot',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
