# Generated by Django 5.1.7 on 2025-04-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0005_customfielddefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='model_type',
            field=models.CharField(blank=True, choices=[('StockData', 'Stock Data'), ('BalanceSheet', 'Balance Sheet'), ('ProfitLossStatement', 'Profit & Loss Statement'), ('CashFlow', 'Cash Flow')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the FAQ question. Symbols like ₹, %, etc. are supported.')),
                ('answer', models.TextField(help_text='Provide a clear, concise answer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
    ]
