# Generated by Django 5.1.7 on 2025-04-12 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0006_customfielddefinition_model_type_faq'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='stock_date',
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='custom_model_name',
            field=models.CharField(blank=True, help_text="Optional custom model name (e.g., 'CustomRatios')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='table_title',
            field=models.CharField(blank=True, help_text="Friendly section title for UI (e.g., 'Operating Metrics')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='stock_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='unlisted_stock_marketplace.stockperiod'),
        ),
        migrations.AddField(
            model_name='stockperiod',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockperiod',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockperiod',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('stock', 'stock_period', 'field_definition')},
        ),
    ]
