# Generated by Django 5.2.2 on 2025-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0006_stockdailysnapshot_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailysnapshot',
            name='lot',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
