# Generated by Django 5.1.7 on 2025-04-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0007_alter_customfieldvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockperiod',
            name='stock',
        ),
    ]
