# Generated by Django 5.2.2 on 2025-06-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0007_alter_stockdailysnapshot_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('dec', 'Decimal'), ('char', 'Text'), ('date', 'Date')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='unlisted_stock_marketplace.stockdata'),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='table_title',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
    ]
