# Generated by Django 5.2.2 on 2025-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0008_customfielddefinition_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('int', 'Integer'), ('dec', 'Decimal'), ('char', 'Text'), ('date', 'Date')], default='dec', help_text='Determines which input type to show in admin', max_length=10),
        ),
    ]
