# Generated by Django 5.1.7 on 2025-04-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0008_remove_stockperiod_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the table display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='table_header',
            field=models.ForeignKey(blank=True, help_text='Group this field under a common table header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='unlisted_stock_marketplace.tableheader'),
        ),
    ]
