# Generated by Django 5.2.2 on 2025-06-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0009_alter_customfielddefinition_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='dec_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
