# Generated by Django 5.1.7 on 2025-04-12 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0009_tableheader_customfielddefinition_table_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='table_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values', to='unlisted_stock_marketplace.tableheader'),
        ),
    ]
