# Generated by Django 5.2.2 on 2025-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0010_alter_customfieldvalue_dec_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate'), ('WhollyOwnedSubsidiary', 'Wholly Owned Subsidiary'), ('StepDownSubsidiary', 'Step Down Subsidiary'), ('JointVenture', 'Joint Venture'), ('Holding', 'Holding')], max_length=30, null=True),
        ),
    ]
