# Generated by Django 5.1.7 on 2025-04-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0010_customfieldvalue_table_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='table_header',
        ),
    ]
