# Generated by Django 5.1.7 on 2025-04-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0011_remove_customfielddefinition_table_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableheader',
            name='stock_period',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this header to a specific stock period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_headers', to='unlisted_stock_marketplace.stockperiod'),
        ),
    ]
