# Generated by Django 5.2.2 on 2025-06-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0011_alter_companyrelation_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
