# Generated by Django 5.2.2 on 2025-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0012_alter_stockhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
