# Generated by Django 5.1.7 on 2025-04-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0012_tableheader_stock_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableheader',
            name='stock_period',
            field=models.ForeignKey(blank=True, help_text='If provided, will override the title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_headers', to='unlisted_stock_marketplace.stockperiod'),
        ),
        migrations.AlterField(
            model_name='tableheader',
            name='title',
            field=models.CharField(blank=True, help_text='Leave blank if stock period is used as title', max_length=255, unique=True),
        ),
    ]
