# Generated by Django 5.2.4 on 2025-07-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0013_alter_stockhistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='gap',
            field=models.PositiveIntegerField(blank=True, help_text='Number of rows per group. First row is the parent.', null=True),
        ),
    ]
