# Generated by Django 5.2.4 on 2025-08-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0014_customfielddefinition_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='hide_company_overview',
            field=models.BooleanField(default=False),
        ),
    ]
