# Generated by Django 5.1.7 on 2025-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0014_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='model_type',
            field=models.CharField(blank=True, choices=[('FinancialRatios', 'Financial Ratios'), ('BalanceSheet', 'Balance Sheet'), ('ProfitLossStatement', 'Profit & Loss Statement'), ('CashFlow', 'Cash Flow')], max_length=50, null=True),
        ),
    ]
