# Generated by Django 5.2.4 on 2025-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0015_stockdata_hide_company_overview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldvalue',
            options={'ordering': ['order'], 'verbose_name': 'Custom Field Value', 'verbose_name_plural': 'Custom Field Values'},
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
