# Generated by Django 5.1.7 on 2025-04-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0015_alter_customfielddefinition_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='stock_period',
        ),
        migrations.RemoveField(
            model_name='profitlossstatement',
            name='stock_period',
        ),
        migrations.DeleteModel(
            name='BalanceSheet',
        ),
        migrations.DeleteModel(
            name='CashFlow',
        ),
        migrations.DeleteModel(
            name='ProfitLossStatement',
        ),
    ]
