# Generated by Django 5.1.7 on 2025-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0016_remove_cashflow_stock_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='gst_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
