# Generated by Django 5.2.4 on 2025-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0016_alter_customfieldvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='partner_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('int', 'Integer'), ('dec', 'Decimal'), ('char', 'Text'), ('date', 'Date')], default='dec', help_text='Determines which value field (int, dec, char, date) to use', max_length=10),
        ),
    ]
