# Generated by Django 5.1.7 on 2025-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0017_stockdata_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
