# Generated by Django 5.2.4 on 2025-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0018_stockhistory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistgroup',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
