# Generated by Django 5.1.7 on 2025-04-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0018_alter_stockdata_gst_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('relation_type', models.CharField(choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate')], max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
    ]
