# Generated by Django 5.2.4 on 2025-09-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0019_wishlistgroup_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='youtube_video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
