# Generated by Django 5.1.7 on 2025-04-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0019_companyrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrelation',
            name='percentage_shares_held',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage (e.g., 75.00)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companyrelation',
            name='relation_type',
            field=models.CharField(choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate'), ('WhollyOwnedSubsidiary', 'Wholly Owned Subsidiary'), ('StepDownSubsidiary', 'Step Down Subsidiary')], max_length=30),
        ),
    ]
