# Generated by Django 5.1.7 on 2025-04-12 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0020_companyrelation_percentage_shares_held_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalBusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_service_name', models.CharField(max_length=255, verbose_name='Name and Description of main products/services')),
                ('nic_code', models.CharField(max_length=20, verbose_name='NIC Code of the product/service')),
                ('turnover_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% to total turnover of the Company')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_activities', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
    ]
