# Generated by Django 5.2.4 on 2025-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0020_stockdata_youtube_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='number_of_times_searched',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
