# Generated by Django 5.2.4 on 2025-09-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0021_alter_stockdata_number_of_times_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholdingpattern',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
