# Generated by Django 5.1.7 on 2025-04-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0021_principalbusinessactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalbusinessactivity',
            name='nic_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIC Code of the product/service'),
        ),
    ]
