# Generated by Django 5.1.7 on 2025-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0022_alter_principalbusinessactivity_nic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelation',
            name='relation_type',
            field=models.CharField(choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate'), ('WhollyOwnedSubsidiary', 'Wholly Owned Subsidiary'), ('StepDownSubsidiary', 'Step Down Subsidiary'), ('JointVenture', 'Joint Venture')], max_length=30),
        ),
    ]
