# Generated by Django 5.2.4 on 2025-09-28 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0022_shareholdingpattern_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholdingpattern',
            name='note',
        ),
        migrations.CreateModel(
            name='ShareholdingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareholding_info', to='unlisted_stock_marketplace.stockdata')),
            ],
        ),
    ]
