# Generated by Django 5.1.7 on 2025-04-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0023_alter_companyrelation_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='subtitle',
            field=models.CharField(blank=True, choices=[('non_current_assets', 'Non Current Assets'), ('current_assets', 'Current Assets'), ('equity', 'Equity'), ('non_current_liabilities', 'Non Current Liabilities'), ('current_liabilities', 'Current Liabilities'), ('income', 'Income'), ('expense', 'Expense'), ('profit', 'Profit'), ('loss', 'Loss'), ('profit_before_exceptional_items_and_tax', 'Profit Before Exceptional Items and Tax'), ('tax_expense', 'Tax Expense'), ('other_comprehensive_income_loss', 'Other Comprehensive Income (Loss)'), ('profit_or_loss', 'Profit or Loss'), ('attributable_to_owners_of_parent', 'Attributable to Owners of Parent'), ('total_other_comprehensive_income', 'Total Other Comprehensive Income'), ('total_comprehensive_income', 'Total Comprehensive Income'), ('earnings_per_share', 'Earnings Per Share')], help_text='Optional subtitle categorization for reporting (e.g., Current Assets, Equity, etc.)', max_length=100, null=True),
        ),
    ]
