# Generated by Django 5.2.4 on 2025-09-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0023_remove_shareholdingpattern_note_shareholdinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='number_of_shares',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='percentage_of_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
