# Generated by Django 5.1.7 on 2025-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0024_customfieldvalue_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('bold_italic', 'Bold & Italic'), ('bold_underline', 'Bold & Underline'), ('italic_underline', 'Italic & Underline'), ('all', 'Bold, Italic & Underline')], default='normal', max_length=30),
        ),
    ]
