# Generated by Django 5.1.4 on 2025-05-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0025_remove_customfieldvalue_subtitle_and_more'),
        ('user_auth', '0004_cmrcopy_cmr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='stock_type',
            field=models.CharField(blank=True, choices=[('Unlisted', 'Unlisted'), ('Angel', 'Angel'), ('Listed', 'Listed')], default='Listed', help_text='Type of stock: Unlisted, Angel, or Listed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.broker'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='days_gain_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='invested_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='number_of_shares',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='overall_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='overall_gain_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale')], default='Purchase', max_length=10),
        ),
    ]
