# Generated by Django 5.1.4 on 2025-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0026_stockdata_stock_type_stocktransaction_avg_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='price_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='price_difference_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
