# Generated by Django 5.1.4 on 2025-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0027_stocktransaction_closing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelation',
            name='company_name',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='companyrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate'), ('WhollyOwnedSubsidiary', 'Wholly Owned Subsidiary'), ('StepDownSubsidiary', 'Step Down Subsidiary'), ('JointVenture', 'Joint Venture')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='name',
            field=models.CharField(max_length=775, unique=True),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='table_title',
            field=models.CharField(blank=True, help_text="Friendly section title for UI (e.g., 'Operating Metrics')", max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='position',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, help_text='Provide a clear, concise answer.', null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, help_text='Enter the FAQ question. Symbols like ₹, %, etc. are supported.', null=True),
        ),
        migrations.AlterField(
            model_name='principalbusinessactivity',
            name='product_service_name',
            field=models.CharField(blank=True, max_length=775, null=True, verbose_name='Name and Description of main products/services'),
        ),
        migrations.AlterField(
            model_name='principalbusinessactivity',
            name='turnover_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% to total turnover of the Company'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='number_of_shares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='percentage_of_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='shareholder_name',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='category',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='company_name',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='scrip_name',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='share_name',
            field=models.CharField(max_length=775),
        ),
        migrations.AlterField(
            model_name='tableheader',
            name='title',
            field=models.CharField(blank=True, help_text='Leave blank if stock period is used as title', max_length=775, unique=True),
        ),
    ]
