# Generated by Django 5.1.4 on 2025-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0030_alter_companyrelation_percentage_shares_held_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelation',
            name='percentage_shares_held',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Enter percentage (e.g., 100 or 100.00)', max_digits=5, null=True),
        ),
    ]
