# Generated by Django 5.1.4 on 2025-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0036_alter_companyrelation_percentage_shares_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelation',
            name='percentage_shares_held',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter percentage (e.g., 75.00)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='shareholdingpattern',
            name='percentage_of_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
