# Generated by Django 5.1.4 on 2025-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0037_alter_companyrelation_percentage_shares_held_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('char', 'Text'), ('int', 'Integer'), ('dec', 'Decimal'), ('date', 'Date')], default='int', max_length=10),
        ),
    ]
