# Generated by Django 5.1.4 on 2025-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0038_alter_customfielddefinition_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='name',
            field=models.CharField(max_length=775),
        ),
    ]
