# Generated by Django 5.1.4 on 2025-05-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0039_alter_customfielddefinition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Optional: Associate this field with a specific stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_definitions', to='unlisted_stock_marketplace.stockdata'),
        ),
    ]
