# Generated by Django 5.1.4 on 2025-05-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0040_customfielddefinition_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='table_header',
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Associate this field with a specific stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='unlisted_stock_marketplace.stockdata'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('bold_italic', 'Bold & Italic')], default='normal', max_length=30),
        ),
    ]
