# Generated by Django 5.1.4 on 2025-05-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0041_remove_customfieldvalue_table_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='field_type',
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('stock_period', 'field_definition')},
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='table_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values', to='unlisted_stock_marketplace.tableheader'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('bold_italic', 'Bold & Italic'), ('bold_underline', 'Bold & Underline'), ('italic_underline', 'Italic & Underline'), ('all', 'Bold, Italic & Underline')], default='normal', max_length=30),
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='stock',
        ),
    ]
