# Generated by Django 5.1.4 on 2025-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0042_remove_customfielddefinition_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='model_type',
            field=models.CharField(blank=True, choices=[('FinancialRatios', 'Financial Ratios'), ('BalanceSheet', 'Balance Sheet'), ('ProfitLossStatement', 'Profit & Loss Statement'), ('CashFlow', 'Cash Flow'), ('DividendHistory', 'Dividend History')], max_length=50, null=True),
        ),
    ]
