# Generated by Django 5.1.4 on 2025-05-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0043_alter_customfielddefinition_model_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldvalue',
            options={'verbose_name': 'Custom Field Value', 'verbose_name_plural': 'Custom Field Values'},
        ),
    ]
