# Generated by Django 5.1.4 on 2025-05-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0044_alter_customfieldvalue_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='stock_period',
        ),
    ]
