# Generated by Django 5.1.4 on 2025-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0045_alter_customfieldvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='name',
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='description',
            field=models.TextField(blank=True, max_length=775, null=True),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='name',
            field=models.CharField(blank=True, max_length=775, null=True),
        ),
    ]
