# Generated by Django 5.1.4 on 2025-05-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0046_remove_customfielddefinition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='parent_field_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_field_values', to='unlisted_stock_marketplace.customfieldvalue'),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='table_title',
            field=models.CharField(blank=True, help_text="Friendly section title for UI (e.g., 'Non-current assets')", max_length=775, null=True),
        ),
    ]
