# Generated by Django 5.1.4 on 2025-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0047_customfieldvalue_parent_field_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline')], default='normal', max_length=30),
        ),
    ]
