# Generated by Django 5.1.4 on 2025-05-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0050_alter_customfieldvalue_text_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic')], default='normal', max_length=30),
        ),
    ]
