# Generated by Django 5.1.4 on 2025-05-11 04:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0052_alter_customfieldvalue_text_style_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('conviction_level', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='unlisted_stock_marketplace.stockdata')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
