# Generated by Django 5.1.4 on 2025-05-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0053_stockdailysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdailysnapshot',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockdailysnapshot',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockdailysnapshot',
            name='share_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name="Today's Opening Price"),
        ),
        migrations.AlterField(
            model_name='stockdailysnapshot',
            name='ltp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Yesterday's Close (LTP)"),
        ),
    ]
