# Generated by Django 5.1.4 on 2025-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0055_wishlistgroup_wishlist_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_type',
            field=models.CharField(blank=True, choices=[('Unlisted', 'Unlisted'), ('Angel', 'Angel'), ('Listed', 'Listed')], default='Unlisted', help_text='Type of stock: Unlisted, Angel, or Listed', max_length=20, null=True),
        ),
    ]
