# Generated by Django 5.1.4 on 2025-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0056_alter_stockdata_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdailysnapshot',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
