# Generated by Django 5.1.4 on 2025-05-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlisted_stock_marketplace', '0057_stockdailysnapshot_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailysnapshot',
            name='ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Yesterday's Close (LTP)"),
        ),
        migrations.AlterField(
            model_name='stockdailysnapshot',
            name='share_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Today's Opening Price"),
        ),
    ]
