# Generated by Django 5.1.4 on 2025-06-08 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_Manager', '0006_alter_advisor_advisor_type_delete_advisortype'),
        ('unlisted_stock_marketplace', '0003_alter_customfieldvalue_text_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMUserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('custom_user_id', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('client_id_input', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('order_id', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('order_type', models.CharField(max_length=10)),
                ('isin_no', models.CharField(blank=True, max_length=20, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buy_status', models.CharField(blank=True, max_length=15, null=True)),
                ('sell_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_status', models.CharField(blank=True, max_length=15, null=True)),
                ('assigned_rm', models.ForeignKey(limit_choices_to={'user_type': 'RM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_viewed_users', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_Manager.broker')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unlisted_stock_marketplace.stockdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_user_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RMPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bank_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('remark', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('rm_user_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='RM_User.rmuserview')),
            ],
        ),
    ]
