# Generated by Django 5.2.2 on 2025-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RM_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmpaymentrecord',
            name='AC_Payment_Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('approved', 'Payment Received'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='rmpaymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('approved', 'Payment Received'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
