# Generated by Django 5.2.2 on 2025-06-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RM_User', '0001_initial'),
        ('site_Manager', '0006_alter_advisor_advisor_type_delete_advisortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmuserview',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_user_views', to='site_Manager.advisor'),
        ),
    ]
