# Generated by Django 5.2.2 on 2025-06-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RM_User', '0002_rmuserview_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmuserview',
            name='advisor',
        ),
    ]
