# Generated by Django 5.2.4 on 2025-08-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RM_User', '0002_rmpaymentrecord_ac_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmpaymentrecord',
            name='paymentConfirmationMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rmpaymentrecord',
            name='payment_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
