# Generated by Django 5.2.4 on 2025-08-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RM_User', '0003_rmpaymentrecord_paymentconfirmationmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmpaymentrecord',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
