# Generated by Django 5.2.4 on 2025-08-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RM_User', '0005_rmpaymentrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmpaymentrecord',
            name='payment_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
