# Generated by Django 5.1.4 on 2025-06-02 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_type', models.CharField(choices=[('Thangiv', 'Thangiv'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('pan', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{3,4}[A-Z]$', 'Enter valid PAN number')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter valid phone number')])),
            ],
        ),
        migrations.CreateModel(
            name='HeroSectionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage Banner', max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
