# Generated by Django 5.1.4 on 2025-06-05 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_id',
            field=models.CharField(help_text='Unique Broker ID (e.g., BRK001)', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter valid phone number')]),
        ),
        migrations.AlterField(
            model_name='broker',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
