# Generated by Django 5.1.4 on 2025-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_type', models.CharField(choices=[('Thangiv', 'Thangiv'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
