# Generated by Django 5.1.4 on 2025-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0002_alter_broker_broker_id_alter_broker_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_id',
            field=models.CharField(help_text='Unique Broker ID (e.g., BRK001)', max_length=50, unique=True),
        ),
    ]
