# Generated by Django 5.1.4 on 2025-06-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0003_broker_id_alter_broker_broker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
