# Generated by Django 5.1.4 on 2025-06-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0004_alter_broker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='advisor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_Manager.advisortype'),
        ),
    ]
