# Generated by Django 5.1.4 on 2025-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0005_advisortype_alter_advisor_advisor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='AdvisorType',
        ),
    ]
