# Generated by Django 5.2.4 on 2025-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0006_alter_advisor_advisor_type_delete_advisortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog_banners/')),
                ('date', models.DateField()),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
