# Generated by Django 5.2.4 on 2025-07-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0007_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
