# Generated by Django 5.2.4 on 2025-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0008_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog_banners/')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
            ],
        ),
    ]
