# Generated by Django 5.2.4 on 2025-08-29 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0010_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='download',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
