# Generated by Django 5.2.4 on 2025-08-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0011_remove_event_download_alter_event_date_time'),
        ('unlisted_stock_marketplace', '0018_stockhistory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unlisted_stock_marketplace.stockdata'),
        ),
    ]
