# Generated by Django 5.2.4 on 2025-09-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0012_event_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a PDF document', null=True, upload_to='events/documents/'),
        ),
    ]
