# Generated by Django 5.2.4 on 2025-09-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_Manager', '0013_event_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
