# Generated by Django 5.1.4 on 2025-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0003_remove_selltransaction_price_per_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
