# Generated by Django 5.1.4 on 2025-06-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0005_buytransaction_status_selltransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selltransaction',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
